apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opinai-sandbox-manager
subjects:
  - kind: ServiceAccount
    name: opinai-controller
    namespace: opinai
roleRef:
  kind: ClusterRole
  name: opinai-sandbox-manager
  apiGroup: rbac.authorization.k8s.io
