apiVersion: v1
kind: Service
metadata:
  name: opinai-controller
  namespace: opinai
  labels:
    app: opinai-controller
spec:
  selector:
    app: opinai-controller
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
